<?php

namespace Miriade\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventUserRepository extends EntityRepository
{
}
