        <div class="col-md-3">
           <div class="well organisateurs-block">
              <h4>Organizateurs</h4>
              <div class="row">
                <div class="col-md-12 organisateurs-block-item">
                  <a href="#">
                      <img class="img-responsive" src="img/220x0_logo_net_en.png" alt="">
                  </a>
                </div>
                <div class="col-md-12 organisateurs-block-item">
                  <a href="#">
                      <img class="img-responsive" src="img/220x0_logo_net_en.png" alt="">
                  </a>
                </div>
                <div class="col-md-12 organisateurs-block-item">
                  <a href="#">
                      <img class="img-responsive" src="img/220x0_logo_net_en.png" alt="">
                  </a>
                </div>
              </div>
              <!-- /.row -->
           </div>
           <div class="well">
              <h4>Vues de profil</h4>
              <div class="row">
                  <table class="table table-condensed">
                    <tr>
                      <td class="col-md-2">Avant l'événement</td>
                      <td class="col-md-1">17218</td>
                    </tr>
                    <tr>
                      <td class="col-md-2">Après l'événement</td>
                      <td class="col-md-1">13285</td>
                    </tr>
                    <tr>
                      <td class="col-md-2">Meetings Accepted</td>
                      <td class="col-md-1">107</td>
                    </tr>
                  </table>
              </div>
              <!-- /.row -->
           </div>
        </div>
      